dist: build/dist
builds:
  - id: release_build
    targets:
      - linux_amd64
    binary: broadtail
    hooks:
      pre: make build-js
nfpms:
  - id: package_nfpms
    package_name: broadtail
    builds:
      - release_build
    vendor: lmika
    homepage: https://github.com/lmika/broadtail
    maintainer: Leon Mika <lmika@lmika.org>
    description: Video download manager
    license: MIT
    formats:
      - deb
      - rpm
    empty_folders:
      - /var/lib/broadtail/
    contents:
      - src: package/broadtail.service
        dst: /etc/systemd/system/broadtail.service
        type: config
release:
  ids:
    - package_nfpms
  draft: true
