dist: build/dist
builds:
  - id: release_build
    targets:
      - linux_amd64
      - linux_arm64
    binary: broadtail
    hooks:
      pre: make build-js
nfpms:
  - id: package_nfpms
    package_name: broadtail
    builds:
      - release_build
    vendor: lmika
    homepage: https://github.com/lmika/broadtail
    maintainer: Leon Mika <lmika@lmika.org>
    description: Video download manager
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: package/broadtail.service
        dst: /etc/systemd/system/broadtail.service
        type: config
      - src: package/config.yaml
        dst: /usr/local/etc/broadtail/config.yaml
        type: "config|noreplace"
      - dst: /var/lib/broadtail/
        type: dir
      - dst: /usr/local/etc/broadtail
        type: dir        
    scripts:
      postinstall: package/postinstall.sh
      preremove: package/preremove.sh
release:
  ids:
    - package_nfpms
  draft: true
